language: c++
sudo: required
services:
  - docker
install:
  - docker build -t arduino_verify . -f Dockerfile.verify
  - docker build -t arduino_uts . -f Dockerfile.unittest
script:
  - docker run arduino_verify
  - docker run arduino_uts
